version: '3.4'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
        container_name: elasticsearch
        ports:
            - 5001:9200
        environment:
            - discovery.type=single-node
            - cluster.name=elasticsearch
            - node.name=elasticsearch
            - discovery.seed_hosts=elasticsearch
            - xpack.security.enabled=false

    fluent-bit:
        image: fluent/fluent-bit
        volumes:
            - ./fluent-bit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
            - ./fluent-bit/conf/parsers.conf:/fluent-bit/etc/parsers.conf
        environment:
            - FLB_ES_HOST=elasticsearch
            - FLB_ES_PORT=9200
        ports:
            - 24224:24224
            - 24224:24224/udp
        depends_on:
            - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.0
        container_name: kibana
        ports:
            - 5003:5601
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - fluent-bit
        logging:
            driver: fluentd
            options:
                tag: application.kibana
    
    postgres:
        build: ./postgres
        image: postgres:15.1
        container_name: postgres
        restart: always
        ports:
            - 5004:5432
        environment:
            - POSTGRES_PASSWORD=appadmin!@#$%
            - POSTGRES_USER=appadmin
            - POSTGRES_DB=application
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c config_file=/etc/conf/postgresql.conf
        depends_on:
            - fluent-bit
        logging:
            driver: fluentd
            options:
                tag: application.postgres
        
    keycloak:
        image: quay.io/keycloak/keycloak:20.0.2
        container_name: keycloak
        ports:
            - 5005:8080
        environment:
            - KEYCLOAK_ADMIN=appadmin
            - KEYCLOAK_ADMIN_PASSWORD=appadmin!@#$%
            - KC_DB=postgres
            - KC_DB_URL_HOST=postgres
            - KC_DB_URL_DATABASE=application
            - KC_DB_USERNAME=appadmin
            - KC_DB_SCHEMA=auth
            - KC_DB_PASSWORD=appadmin!@#$%
            - KC_HEALTH_ENABLED=true
            - KC_METRICS_ENABLED=true
        command: start-dev --log=console  
        depends_on:
            - postgres
            - fluent-bit
        logging:
            driver: fluentd
            options:
                tag: application.keycloak

    catalog.api:
        build:
            context: .
            dockerfile: ./catalog/app/Catalog.Api/Dockerfile
        image: catalog.api:1.1
        container_name: catalog.api
        ports:
            - 5006:5006
            - 5007:5007
        depends_on:
            - postgres
            - fluent-bit
        volumes:
            - file_data:/var/lib/files/data
        logging:
            driver: fluentd
            options:
                tag: application.catalog.api
    
volumes:
  postgres_data:
      driver: local
  file_data:
      driver: local